name: LeyenduxForgeChecker
main: leyendux.github.io.forgechecker.Main
version: ${project.version}

description: Plugin made to check forge mods of all players from the server.
author: Leyendux
website: https://github.com/Leyendux

commands:
  forgecheck:
    description: Check if a player is using Forge
    permission: uhc.mod
    permission-message: §cThis command is only made for mods, sorry!
    usage: §c/<command> [player]